// Generated by CoffeeScript 1.7.1
(function() {
  window.App || (window.App = {});

  App.fns = {
    buildPlayerList: function() {
      var player, team, _i, _j, _len, _len1, _ref, _ref1;
      App.allPlayers = [];
      _ref = App.league.teams;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        team = _ref[_i];
        _ref1 = team.players;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          player = _ref1[_j];
          App.allPlayers.push(player);
        }
      }
      return App.allPlayers = new Players(App.allPlayers);
    }
  };

}).call(this);
