// Generated by CoffeeScript 1.7.1
(function() {
  window.App || (window.App = {});

  App.fns = {
    buildPlayerList: function() {
      var $select, htmlStr, player, team, _i, _j, _len, _len1, _ref, _ref1;
      if (App.league.teams.every("players")) {
        App.allPlayers = [];
        _ref = App.league.teams;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          team = _ref[_i];
          _ref1 = team.players;
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            player = _ref1[_j];
            player.name = player.player;
            App.allPlayers.push(player);
          }
        }
        App.allPlayers = new Collection(App.allPlayers);
        htmlStr = "<select id='player-select' class='player-select'>";
        App.allPlayers.each(function(p) {
          return htmlStr += "<option value='" + p.playerId + "'>" + p.name + "</option>";
        });
        htmlStr += "</select>";
        return $select = $(htmlStr).prependTo($("body")).on("change", function(event) {
          player = App.allPlayers.findWhere({
            playerId: +this.value
          });
          return player.getPlayerShots().then(function(player) {
            return player.drawShootingChart();
          });
        });
      }
    }
  };

}).call(this);
