// Generated by CoffeeScript 1.7.1
(function() {
  App.league = new App.League();

  App.league.getLeagueSportVuData();

  App.league.getLeagueShots().then(function(league) {
    console.log(league.unbinnedShots);
    return App.drawD3(league.unbinnedShots);
  });

}).call(this);
