// Generated by CoffeeScript 1.7.1
(function() {
  App.binConfig = {
    dim1: "x",
    dim2: "y",
    dim1size: 10,
    dim2size: 10,
    threshold: 20
  };

  App.league = new App.League();

  App.league.getLeagueSportVuData();

  App.league.getLeagueShots().then(function(league) {
    return App.drawD3(league.unbinnedShots);
  });

  App.league.getLeagueTeams().then(function() {
    var league;
    league = arguments[0];
    return league.teams.each(function(team) {
      return team.getTeamPlayers().then(function() {});
    });
  });

}).call(this);
