// Generated by CoffeeScript 1.7.1
(function() {
  var League, Model, Player, Players, Shot, Shots, Team, Teams,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.App || (window.App = {});

  Model = (function() {
    function Model(model) {
      var key, val;
      for (key in model) {
        val = model[key];
        this[key] = val;
      }
    }

    return Model;

  })();

  App.League = League = (function(_super) {
    __extends(League, _super);

    function League() {
      return League.__super__.constructor.apply(this, arguments);
    }

    League.prototype.getLeagueTeams = function() {
      return App.ajax.getLeagueTeams().then((function(_this) {
        return function(teams) {
          _this.teams = new Teams(teams);
          return _this;
        };
      })(this));
    };

    return League;

  })(Model);

  App.Team = Team = (function(_super) {
    __extends(Team, _super);

    function Team() {
      return Team.__super__.constructor.apply(this, arguments);
    }

    Team.prototype.getTeamPlayers = function() {
      return App.ajax.getTeamPlayers(this.teamId).then((function(_this) {
        return function(players) {
          _this.players = new Players(players);
          if (App.league.teams.every("players")) {
            App.fns.buildPlayerList();
          }
          return _this;
        };
      })(this));
    };

    return Team;

  })(Model);

  App.Player = Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      return Player.__super__.constructor.apply(this, arguments);
    }

    Player.prototype.getPlayerShots = function() {
      return App.ajax.getPlayerShots(this.playerId).then((function(_this) {
        return function(shots) {
          _this.shots = new Shots(shots);
          return _this;
        };
      })(this));
    };

    return Player;

  })(Model);

  App.Shot = Shot = (function(_super) {
    __extends(Shot, _super);

    function Shot() {
      return Shot.__super__.constructor.apply(this, arguments);
    }

    return Shot;

  })(Model);

  App.Teams = Teams = (function(_super) {
    __extends(Teams, _super);

    function Teams(models) {
      var col, model;
      col = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = models.length; _i < _len; _i++) {
          model = models[_i];
          _results.push(new Team(model));
        }
        return _results;
      })();
      Teams.__super__.constructor.call(this, col);
    }

    return Teams;

  })(Collection);

  App.Players = Players = (function(_super) {
    __extends(Players, _super);

    function Players(models) {
      var col, model;
      col = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = models.length; _i < _len; _i++) {
          model = models[_i];
          _results.push(new Player(model));
        }
        return _results;
      })();
      Players.__super__.constructor.call(this, col);
    }

    return Players;

  })(Collection);

  App.Shots = Shots = (function(_super) {
    __extends(Shots, _super);

    function Shots(models) {
      var col, model;
      col = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = models.length; _i < _len; _i++) {
          model = models[_i];
          _results.push(new Shot(model));
        }
        return _results;
      })();
      Shots.__super__.constructor.call(this, col);
    }

    return Shots;

  })(Collection);

}).call(this);
