// Generated by CoffeeScript 1.7.1
(function() {
  var camelize, cleanPropNames, collectify, prototypeChain;

  window.App || (window.App = {});

  camelize = function(str) {
    str = str.replace(/([^a-zA-Z0-9_\- ])|^[_0-9]+/g, "").trim().toLowerCase();
    return str = str.replace(/([_-]+)([a-zA-Z0-9])/g, function(a, b, c) {
      return c.toUpperCase();
    });
  };

  collectify = function(headers, arrays) {
    var array, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = arrays.length; _i < _len; _i++) {
      array = arrays[_i];
      _results.push(_.object(headers, array));
    }
    return _results;
  };

  cleanPropNames = function(obj) {
    var key, ret, val;
    ret = {};
    for (key in obj) {
      val = obj[key];
      ret[camelize(key)] = val;
    }
    return ret;
  };

  prototypeChain = function(obj) {
    var chain;
    chain = [];
    while ((obj = Object.getPrototypeOf(obj))) {
      chain.push(obj);
    }
    return chain;
  };

  App.util = {
    camelize: camelize,
    collectify: collectify,
    cleanPropNames: cleanPropNames,
    prototypeChain: prototypeChain
  };

}).call(this);
